GHA audit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -84,6 +84,21 @@ jobs:
           commit_message: ${{ github.event.head_commit.message }}
           force_orphan: true
 
+      - name: CHECK - pnpm audit inline (prod deps only)
+        if: ${{ github.actor == 'dependabot[bot]' || !(github.event_name == 'pull_request') }}
+        run: |
+          pnpm audit --prod --audit-level=high > audit.txt && echo "::info::✅ No vulnerabilities found" || (echo "::warning::❌ Vulnerabilities found";cat audit.txt)
+
+      - name: CHECK - pnpm audit and comment on PR
+        if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request }}
+        uses: JamesRobertWiseman/pnpm-audit@v3
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          level: moderate   # 'low'|'moderate'|'high'|'critical'
+          fails: false # true to fail the build if vulnerabilities are found
+          single_comment: true # true to only post one comment
+          inline: true # true to emit audit findings directly in the workflow logs using GitHub annotation syntax
+
       - name: PACKAGE - PUBLISH - NpmJS package
         if: github.ref == 'refs/heads/npmjs'
         run: |
